form:
  method: "get"
  path: "/form"
  controller: "FormController"
  function: "index"
  auth: true

# Media Online
berita:
  admin: true

kategori:
  admin: true

folder:
  admin: true

# Seting
users:
  admin: true

grup:
  admin: true

# Publik
landing:
  method: "get"
  path: "/"
  controller: "LandingController"
  function: "index"
  auth: false
